version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ocr-sam-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x5usdugsgpkc"
s3_prefix = "ocr-sam-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=dev",
    "S3BucketName=ocr-legal-documents-dev",
    "MistralApiKey=fIGM8jrDAuWDzHnidpTJ8sJBWXHXx3qg",
    "CreatioUrl=https://dev-global-bank.creatio.com/",
    "CreatioUsername=Edwin Penalba", 
    "CreatioPassword=Ciber2025*",
    "EnableDynamoDB=true"
]
[y.deploy.parameters]
stack_name = "ocr-sam-stack"
resolve_s3 = true
s3_prefix = "ocr-sam-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\" S3BucketName=\"ocr-legal-documents-dev\" CreatioUrl=\"https://dev-global-bank.creatio.com/" CreatioUsername=\"Edwin Penalba\" EnableDynamoDB=\"true\""
image_repositories = []
